# Generated by Django 4.1.3 on 2023-08-24 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField(null=True)),
                ('links', models.JSONField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='project/attachment/')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='project/cover/')),
                ('collaborators', models.JSONField(blank=True, null=True)),
                ('isPublished', models.BooleanField(default=False)),
                ('current_status', models.TextField(blank=True, null=True)),
                ('status_updated_at', models.DateTimeField()),
                ('status', models.CharField(choices=[(1, 'In Progress'), (2, 'Under Review'), (3, 'Completed')], default=1, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='proposal/attachment/')),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField()),
                ('state', models.CharField(choices=[(1, 'In Progress'), (2, 'Approved'), (3, 'Rejected'), (4, 'Frozen')], default=1, max_length=2)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('remark_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
